import { mkdirSync, writeFileSync } from "node:fs";
import { homedir } from "node:os";
import { dirname, join } from "node:path";
import { type CommandContext, registerCommandHandler } from "../lib/cli";

const SOURCE_LINE = "source-file ~/.config/tp/tmux.conf";
const WINDOW_STATUS_BASE = "#I:#W#{?window_flags,#{window_flags}, }";
const STATE_MARKER =
	"#{?@pi_state,#{?#{==:#{@pi_state},blocked},#[fg=yellow]⏸#[default],#{?#{==:#{@pi_state},tool},#[fg=cyan]●#[default],#{?#{==:#{@pi_state},thinking},#[fg=blue]●#[default],#{?#{==:#{@pi_state},idle},#[fg=colour244]○#[default],}}}},}";
const WINDOW_STATUS_FORMAT = `${WINDOW_STATUS_BASE}${STATE_MARKER}`;

const GENERATED_TMUX_CONFIG = [
	"# Generated by tp bind. Do not edit.",
	"",
	'bind T display-popup -E "tp pop"',
	'bind B run-shell "tp b -g || true"',
	"",
	`set -g window-status-format '${WINDOW_STATUS_FORMAT}'`,
	`set -g window-status-current-format '${WINDOW_STATUS_FORMAT}'`,
	"",
	"# Pane borders are off by default. Uncomment both lines below to show the Pi label and state.",
	"# set -g pane-border-status top",
	"# set -g pane-border-format '#{?@pi_state,Pi: #{@pi_state},}'",
	"",
].join("\n");

function configPath(): string {
	const configHome =
		process.env.XDG_CONFIG_HOME ||
		join(process.env.HOME || homedir(), ".config");
	return join(configHome, "tp", "tmux.conf");
}

function bindCommand(context: CommandContext): number {
	if (context.args.options.print === true) {
		context.stdout(GENERATED_TMUX_CONFIG);
		return 0;
	}

	const path = configPath();
	mkdirSync(dirname(path), { recursive: true });
	writeFileSync(path, GENERATED_TMUX_CONFIG, "utf8");
	context.stdout(GENERATED_TMUX_CONFIG);
	const sourceLine = process.env.XDG_CONFIG_HOME
		? `source-file ${path}`
		: SOURCE_LINE;
	context.stdout(`${sourceLine}\n`);
	return 0;
}

export function registerBindCommands(): void {
	registerCommandHandler("bind", bindCommand);
}
