import { CliUsageError, type CommandContext } from "../lib/cli";

export const COMPLETION_INSTALL_HINTS = {
	fish: "# Install: mkdir -p ~/.config/fish/completions && tp completions fish > ~/.config/fish/completions/tp.fish",
	bash: "# Install: tp completions bash >> ~/.bash_completion",
	zsh: "# Install: mkdir -p ~/.zsh/completions && tp completions zsh > ~/.zsh/completions/_tp",
} as const;

const GENERATED_HEADER =
	"# Generated by tp. tp suggestions come from tp __complete; tp-shot flags are static.";

function fishShim(): string {
	return [
		COMPLETION_INSTALL_HINTS.fish,
		GENERATED_HEADER,
		"function __tp_complete_dynamic",
		"    set -l words (commandline -opc)",
		"    set -l current (commandline -ct)",
		"    command tp __complete fish -- $words $current 2>/dev/null",
		"end",
		"complete -c tp -f -a '(__tp_complete_dynamic)'",
		"",
		"# tp-shot has a small static flag surface.",
		"complete -c tp-shot -s h -l help -d 'Show usage'",
		"complete -c tp-shot -l host -r -d 'SSH host or alias'",
		"complete -c tp-shot -l async -d 'Upload in the background'",
		"complete -c tp-shot -l notify-test -d 'Send a test notification'",
		"complete -c tp-shot -l transport -xa 'ssh taildrive' -d 'Upload transport'",
		"complete -c tp-shot -s V -l version -d 'Show version'",
		"",
	].join("\n");
}

function bashShim(): string {
	return [
		COMPLETION_INSTALL_HINTS.bash,
		GENERATED_HEADER,
		"_tp_complete() {",
		'    local cur="${COMP_WORDS[COMP_CWORD]}"',
		"    local -a args=(tp)",
		"    local i suggestion",
		'    for ((i=1; i<COMP_CWORD; i++)); do args+=("${COMP_WORDS[i]}"); done',
		"    COMPREPLY=()",
		"    while IFS=$'\\t' read -r suggestion _; do",
		'        [[ -n "$suggestion" ]] && COMPREPLY+=("$suggestion")',
		'    done < <(tp __complete bash -- "${args[@]}" "$cur" 2>/dev/null)',
		"}",
		"complete -F _tp_complete tp",
		"",
	].join("\n");
}

function zshShim(): string {
	return [
		COMPLETION_INSTALL_HINTS.zsh,
		"#compdef tp",
		GENERATED_HEADER,
		"_tp_complete() {",
		"    local -a replies",
		'    replies=("${(@f)$(tp __complete zsh -- "${words[@]}" 2>/dev/null)}")',
		"    local reply",
		'    for reply in "${replies[@]}"; do',
		"        compadd -- \"${reply%%$'\\t'*}\"",
		"    done",
		"}",
		"compdef _tp_complete tp",
		"",
	].join("\n");
}

export function renderCompletionShim(shell: string): string {
	switch (shell) {
		case "fish":
			return fishShim();
		case "bash":
			return bashShim();
		case "zsh":
			return zshShim();
		default:
			throw new CliUsageError("Usage: tp completions <fish|bash|zsh>");
	}
}

export function completionsCommand(context: CommandContext): number {
	const shell = context.args.positionals[0];
	if (!shell || context.args.positionals.length !== 1)
		throw new CliUsageError("Usage: tp completions <fish|bash|zsh>");
	context.stdout(renderCompletionShim(shell));
	return 0;
}
