import { expect, test } from "bun:test";
import {
	existsSync,
	mkdtempSync,
	readFileSync,
	readdirSync,
	rmSync,
} from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { ScratchTmuxServer, runTp, waitFor } from "./harness";

function temporaryHome(): string {
	return mkdtempSync(join(tmpdir(), "tp-bind-home-"));
}

test("generated tmux config sources cleanly", async () => {
	const home = temporaryHome();
	const configHome = join(home, "xdg");
	const server = new ScratchTmuxServer();
	server.start();
	server.run(["new-session", "-d", "-s", "bind-test"]);
	try {
		const result = await runTp(["bind"], {
			env: { HOME: home, XDG_CONFIG_HOME: configHome },
		});
		expect(result.exitCode).toBe(0);
		const path = join(configHome, "tp", "tmux.conf");
		const source = server.run(["source-file", path]);
		expect(source.stdout).toBe("");
		expect(source.stderr).toBe("");
		expect(result.stdout).toEndWith(`source-file ${path}\n`);
	} finally {
		server.teardown();
		rmSync(home, { recursive: true, force: true });
	}
});

test("window status shows blocked Pi state but leaves plain windows unchanged", async () => {
	const home = temporaryHome();
	const server = new ScratchTmuxServer();
	server.start();
	server.run(["new-session", "-d", "-s", "bind-test"]);
	try {
		const result = await runTp(["bind"], {
			env: { HOME: home, XDG_CONFIG_HOME: undefined },
		});
		expect(result.exitCode).toBe(0);
		expect(result.stdout).toEndWith("source-file ~/.config/tp/tmux.conf\n");
		const path = join(home, ".config", "tp", "tmux.conf");
		server.run(["source-file", path]);
		const fake = server.createFakePi({ state: "blocked" });
		waitFor(() => fake.options()["@pi_state"] === "blocked");
		const plain = `plain-${process.pid}`;
		server.run(["new-session", "-d", "-s", plain]);
		const format = server
			.run(["show-option", "-gv", "window-status-format"])
			.stdout.trim();
		const piWindow = server.run([
			"list-windows",
			"-t",
			`=${fake.sessionName}`,
			"-F",
			format,
		]).stdout;
		const plainWindow = server.run([
			"list-windows",
			"-t",
			`=${plain}`,
			"-F",
			format,
		]).stdout;
		expect(piWindow).toContain("⏸");
		expect(plainWindow).not.toContain("⏸");
		expect(plainWindow).not.toContain("●");
		expect(plainWindow).not.toContain("○");
	} finally {
		server.teardown();
		rmSync(home, { recursive: true, force: true });
	}
});

test("--print writes no files", async () => {
	const home = temporaryHome();
	try {
		const result = await runTp(["bind", "--print"], {
			env: { HOME: home, XDG_CONFIG_HOME: undefined },
		});
		expect(result.exitCode).toBe(0);
		expect(result.stderr).toBe("");
		expect(result.stdout).toContain('bind T display-popup -E "tp pop"');
		expect(result.stdout).toContain("window-status-format");
		expect(readdirSync(home)).toEqual([]);
		expect(existsSync(join(home, ".config", "tp", "tmux.conf"))).toBe(false);
	} finally {
		rmSync(home, { recursive: true, force: true });
	}
});

test("generated config has a stable snapshot", async () => {
	const home = temporaryHome();
	try {
		const configHome = join(home, "config");
		const result = await runTp(["bind"], {
			env: { HOME: home, XDG_CONFIG_HOME: configHome },
		});
		expect(result.exitCode).toBe(0);
		const path = join(configHome, "tp", "tmux.conf");
		const first = readFileSync(path, "utf8");
		const secondResult = await runTp(["bind"], {
			env: { HOME: home, XDG_CONFIG_HOME: configHome },
		});
		expect(secondResult.exitCode).toBe(0);
		expect(readFileSync(path, "utf8")).toBe(first);
		const content = first.replaceAll(home, "<HOME>");
		expect(content).toMatchInlineSnapshot(`
		"# Generated by tp bind. Do not edit.
		
		bind T display-popup -E "tp pop"
		bind B run-shell "tp b -g || true"
		
		set -g window-status-format '#I:#W#{?window_flags,#{window_flags}, }#{?@pi_state,#{?#{==:#{@pi_state},blocked},#[fg=yellow]⏸#[default],#{?#{==:#{@pi_state},tool},#[fg=cyan]●#[default],#{?#{==:#{@pi_state},thinking},#[fg=blue]●#[default],#{?#{==:#{@pi_state},idle},#[fg=colour244]○#[default],}}}},}'
		set -g window-status-current-format '#I:#W#{?window_flags,#{window_flags}, }#{?@pi_state,#{?#{==:#{@pi_state},blocked},#[fg=yellow]⏸#[default],#{?#{==:#{@pi_state},tool},#[fg=cyan]●#[default],#{?#{==:#{@pi_state},thinking},#[fg=blue]●#[default],#{?#{==:#{@pi_state},idle},#[fg=colour244]○#[default],}}}},}'
		
		# Pane borders are off by default. Uncomment both lines below to show the Pi label and state.
		# set -g pane-border-status top
		# set -g pane-border-format '#{?@pi_state,Pi: #{@pi_state},}'
		"
	`);
	} finally {
		rmSync(home, { recursive: true, force: true });
	}
});
